name: null
favicon: null
layout_spectrum: 0.40529
typography_spectrum: 0.54564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f0adb2'
    - '#e94586'
    - '#8e7783'
    - '#574949'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
