name: generative
favicon: null
layout_spectrum: 0.85856
typography_spectrum: 0.14924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f0adb2'
    - '#e94586'
    - '#8e7783'
    - '#574949'
  brandStrength: 0.8125
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
